### PR TITLE
Feature: React router 

### PR DESCRIPTION
**Pull request by c4kaci**
Added:
- react-router-dom
- Nav, Home, About components

WARNING: UXP debugger error

### CODE REVIEW

**Comment by c4kaci** [comment]
Hi @thejustinwalsh ,

I have a UXP debugger error what I couldn't solve.

-------------------------------------------------------------------------------------------
_index.js:10216 Uncaught TypeError: Cannot read property 'length' of undefined
    at createBrowserHistory (VM21157 index.js:10216)
    at new BrowserRouter (VM21157 index.js:38903)
    at constructClassInstance (VM21157 index.js:25022)
    at updateClassComponent (VM21157 index.js:29731)
    at beginWork (VM21157 index.js:31379)
    at e.exports.callCallback (VM21157 index.js:16251)
    at uxp://uxp-internal/domjs_scripts.js:2
    at I (uxp://uxp-internal/domjs_scripts.js:2)
    at uxp://uxp-internal/domjs_scripts.js:2
    at Object.O [as dispatchInternalEvent] (uxp://uxp-internal/domjs_scripts.js:2)_

_The above error occurred in the <BrowserRouter> component:
    at BrowserRouter (index.js:38902:35)
    at div
    at div
    at div
    at App
Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries._


If I use same code for a simple React project it works well.
I'm newbie in React. 
Could you help me in this issue? 

Best regards
Karoly

**Comment by thejustinwalsh** [comment]
Hey! I'll take a look this weekend! Been pushing hard at my 9-5, expecting to spend some time on this next week!

**Comment by thejustinwalsh** [comment]
I am not sure that `react-router-dom` would be the best choice for use in UXP projects...
I would try importing `react-router` and using [MemoryRouter](https://reactrouter.com/web/api/MemoryRouter) instead.

**Comment by c4kaci** [comment]
Hi Justin,

Sorry, but I could not answer. 
To better understand what I meant I attached some screenshots from my pure javascript project.






I need to manage some dynamically generated content. 

Maybe [Top Nav](https://opensource.adobe.com/spectrum-web-components/components/top-nav) control can replace Tabs.
The advantage of tabs is that they can be scrolled between them because they retain their content and there is no need to send a new request to the application server.

Unfortunately, I am just a novice WEB developer. I have worked in C ++ and Java so far.

**Comment by thejustinwalsh** [comment]
Gotcha. 

I am suggesting that you configure react router to use the memory router implementation that does not require an address bar and history to function. It is a minor change, and I linked the docs.

I can include react-router in the demo using the memory router but have been busy myself and will need some time to update the demo.

**Comment by c4kaci** [comment]
On the next week I will go to hospital.  
This is approx. 3-4 weeks so there is no hurry.

**Pull request closed without merging**
